# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1whCp-5bWnbXTVyrSI9pVfWH0sKj2ou3R
"""

# Erkaklar va ayollar sonini foydalanuvchidan so'rash
erkaklar_soni = int(input("O'zbekistondagi erkaklar sonini kiriting: "))
ayollar_soni = int(input("O'zbekistondagi ayollar sonini kiriting: "))

# Erkaklar va ayollar sonini chiqarish
print(f"O'zbekistondagi erkaklar soni: {erkaklar_soni}")
print(f"O'zbekistondagi ayollar soni: {ayollar_soni}")

# Jami aholining soni
jami_aholi = erkaklar_soni + ayollar_soni
print(f"O'zbekistondagi jami aholi soni: {jami_aholi}")